const mongoose = require('mongoose');

/**
 * @swagger
 * components:
 *   schemas:
 *     Journal:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *         userId:
 *           type: string
 *         positionId:
 *           type: string
 *         autoPrompt:
 *           type: string
 *           description: Dynamic behavioral reflection question
 *         reflection:
 *           type: string
 *           description: User's written response to the prompt
 *         tradeOutcome:
 *           type: string
 *           enum: [WIN, LOSS, NEAR_MISS]
 *         isRead:
 *           type: boolean
 *           description: Whether the user has seen this journal entry
 *         createdAt:
 *           type: string
 *           format: date-time
 */
const journalSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    positionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Position',
      required: true,
    },
    /**
     * Dynamically generated prompt based on trade outcome.
     * Generated by journalService.generatePrompt().
     */
    autoPrompt: {
      type: String,
      required: true,
    },
    /**
     * User's reflection text — filled in later via PUT /api/journal/:id.
     * null until the user responds.
     */
    reflection: {
      type: String,
      default: null,
      maxlength: [2000, 'Reflection cannot exceed 2000 characters'],
    },
    tradeOutcome: {
      type: String,
      enum: ['WIN', 'LOSS', 'NEAR_MISS'],
      required: true,
    },
    /**
     * Notification flag for the frontend — false until user views the entry.
     */
    isRead: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

// Index for quick user journal lookups (most recent first)
journalSchema.index({ userId: 1, createdAt: -1 });

module.exports = mongoose.model('Journal', journalSchema);
